name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    # Step 3
    - name: Going to the GameHub Directory
      run: cd GameHub

    # Step 4: Install Node.js dependencies
    - name: Installing Node.js dependencies
      run: npm install

    # Step 5: Run Node.js tests
    - name: Running Node.js tests
      run: npm test
