name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install Node.js dependencies
    - name: Installing Node.js dependencies
      run: |
        cd GameHub
        npm install

    # Step 4: Run Node.js tests
    - name: Running Node.js tests
      run: |
        cd GameHub
        npm test
