name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
          - uses: actions/checkout@v4
    - id: quality-gate
      uses: EffectiveRange/python-verify-github-action@v1
      with:
        python-version: '3.12'
        coverage-threshold: '95'
        add-coverage-comment: 'true'
    - run: echo "Current code coverage is $COVERAGE_PERCENT%"
      shell: bash
      env:
        COVERAGE_PERCENT: ${{ steps.quality-gate.outputs.coverage }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        cd api
        pip install -r requirements.txt
        # Add other dependencies here if needed

    - name: Run tests
      run: pytest
